REFRESH MATERIALIZED VIEW mf_classified;
REFRESH MATERIALIZED VIEW mf_increased;
REFRESH MATERIALIZED VIEW mf_decreased;
REFRESH MATERIALIZED VIEW mf_fresh;
REFRESH MATERIALIZED VIEW mf_exit;
REFRESH MATERIALIZED VIEW mf_drilldown;